- README.adoc
- docs/AboutUs.adoc
- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
> trim trailing spaces

- src/main/java/seedu/address/logic/commands/EditGroupCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/group/Group.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Added new command and parser. 
Edit ModelManager.java and AddressBook.java to add Group functions. 
(TO DO: Refactor group and person functions --> OOP style - functions inside Person/Group objects instead)
> Add EditGroupCommand and Parser

- src/main/java/seedu/address/logic/commands/EditGroupCommand.java
- src/main/java/seedu/address/logic/commands/RegisterCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java
- src/main/java/seedu/address/logic/parser/RegisterCommandParser.java
- src/main/java/seedu/address/model/UniqueList.java
- src/main/java/seedu/address/model/group/Group.java
Edit Group getGroupMember function 
Add RegisterCommand and Parser
> Add RegisterCommand and Parser

- src/main/java/seedu/address/commons/events/ui/GroupPanelSelectionChangedEvent.java
- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/ui/GroupCard.java
- src/main/java/seedu/address/ui/GroupListPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/GroupListCard.fxml
- src/main/resources/view/GroupListPanel.fxml
- src/main/resources/view/MainWindow.fxml
> Add UI for GroupList

- src/main/java/seedu/address/logic/commands/AddTimetableCommand.java
- src/main/java/seedu/address/logic/commands/DownloadTimetableCommand.java
- src/main/java/seedu/address/logic/parser/AddTimetableCommandParser.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/timetable/Timetable.java
- src/main/java/seedu/address/storage/XmlAdaptedPerson.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
> edit constructor of timetable

- src/main/java/seedu/address/logic/commands/AddTimetableCommand.java
> fix typos in usage instructions in add_timetable

- docs/DeveloperGuide.adoc
> testing commit

- docs/UserGuide.adoc
> fix typos and add tag v1.1

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/CreateCommand.java
- src/main/java/seedu/address/model/accounts/Accounts.java
- update command guide for "create" and "login" function
> this commit resolves #39 - Update UserGuide

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
Updated User Guide & Developer Guide for friends features
Design considerations is excluded in this PR
> UG & DG: Friend Features

- src/main/java/seedu/address/logic/commands/CommandUtil.java
- src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/EditGroupCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
> this commit resolves #135, #138

- .travis.yml
- build.gradle
- docs/Timetable.html
- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/DeleteTimetableCommand.java
- src/main/java/seedu/address/logic/commands/DownloadTimetableCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/logic/commands/DownloadTimetableCommandTest.java
fix bug encountered in testing today
> this commit resolves #100 1,6

- src/main/java/seedu/address/commons/util/StringUtil.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- src/test/java/systemtests/AddCommandSystemTest.java
FindCommand: BugFix (find a/gardens) 
error: regex split didn't consider comma
Addcommand: added 'optional add' + test
> FindCommand & AddCommand Update

- docs/UserGuide.adoc
> update user guide

- docs/team/souless94.adoc
- src/main/java/seedu/address/model/person/timetable/TimetableData.java
fix bug, because opencsv cannot read "".
> fix bug for reading timetable from csv file

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/RedoCommand.java
- src/main/java/seedu/address/logic/commands/SelectCommand.java
- src/main/java/seedu/address/logic/commands/UndoCommand.java
Change 'address book' to 'NUS Hangs' in crucial messages
> Update UG & DG

- docs/DeveloperGuide.adoc
- src/main/java/seedu/address/model/person/timetable/TimetableData.java
add tag for developer guide
change name of logger to timetable
> minor fixes

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
> DG&UG: Update tag

- docs/UserGuide.adoc
- docs/team/ZhiWei94.adoc
> ZhiWei.adoc: update PPP

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/systemtests/FindCommandSystemTest.java
> add author for ZhiWei94

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
> fix typo in UG

- docs/AboutUs.adoc
- docs/DeveloperGuide.adoc
- src/test/java/systemtests/AddCommandSystemTest.java
Missing user stories for 'So that I can' for 'add a person'
> DeveloperGuide: Update DG for User Stories

- docs/DeveloperGuide.adoc
Added 'reasons for implementation' for person features
> DG: Update Person Feature
